# Generated by Django 2.1.7 on 2019-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact_specific',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
