# Generated by Django 2.1.7 on 2019-04-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_img_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
