# Generated by Django 2.1.7 on 2019-04-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_img_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
