# Generated by Django 2.1.7 on 2019-04-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190419_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
