# Generated by Django 2.1.7 on 2019-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190419_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='option_bool',
            field=models.BooleanField(default=False),
        ),
    ]
